// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm4bFukBlMXeLS3xKse6RFHTAxY9vkAtQ',
    appId: '1:129626044436:web:2fe6f488bb83e319a50f01',
    messagingSenderId: '129626044436',
    projectId: 'creartive-5fb90',
    authDomain: 'creartive-5fb90.firebaseapp.com',
    storageBucket: 'creartive-5fb90.firebasestorage.app',
    measurementId: 'G-J2G2XX88QB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc52OpkbM_XyNh_AENcS7UIJyyn4kq1hs',
    appId: '1:129626044436:android:4d2a441147625c6ba50f01',
    messagingSenderId: '129626044436',
    projectId: 'creartive-5fb90',
    storageBucket: 'creartive-5fb90.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9gkKlcYbRdEe_fNAJXg8gVVRSAZ-yteE',
    appId: '1:129626044436:ios:19d4bb2c6ab6b154a50f01',
    messagingSenderId: '129626044436',
    projectId: 'creartive-5fb90',
    storageBucket: 'creartive-5fb90.firebasestorage.app',
    iosBundleId: 'com.example.creartive',
  );

}